// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AndroidNDK_GCC_To_Clang.djinni

#import <Foundation/Foundation.h>
@class EXTestCpp;


@interface EXTestCpp : NSObject

+ (nullable EXTestCpp *)create;

- (nonnull NSString *)getStringTest;

@end
