// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AndroidNDK_GCC_To_Clang.djinni

#pragma once

#include <memory>
#include <string>

namespace example {

class TestCpp {
public:
    virtual ~TestCpp() {}

    static std::shared_ptr<TestCpp> create();

    virtual std::string getStringTest() = 0;
};

}  // namespace example
